ALTER TABLE content_pages
  ADD COLUMN image_url VARCHAR(500) NULL AFTER content,
  ADD COLUMN image_alt VARCHAR(255) NULL AFTER image_url;

CREATE TABLE board_members (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(150) NOT NULL,
  role_title VARCHAR(150) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  image_alt VARCHAR(255) NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  updated_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_board_members_sort (sort_order, id),
  CONSTRAINT fk_board_members_admin FOREIGN KEY (updated_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
